name: books_app
description: Teste para UDS - Flutter.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  retrofit: '>=3.0.0 <4.0.0'
  dio: ^4.0.6
  shared_preferences: ^2.0.6
  fluttertoast: ^8.2.2
  provider: ^6.0.1
  url_launcher: ^6.1.11

  flutter:
    sdk: flutter

dev_dependencies:
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.3.0 <4.0.0' 
  json_serializable: '>4.4.0'

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
